/* AUTO-GENERATED. Re-exports the JSON Schema and family dictionaries as objects. Data only, no logic. */
import datasheetSchema from '../../schema/datasheet-1.0.schema.json' with { type: 'json' };
import adcDictionary from '../../dictionary/adc-1.0.json' with { type: 'json' };
import analogSwitchDictionary from '../../dictionary/analog_switch-1.0.json' with { type: 'json' };
import bjtDictionary from '../../dictionary/bjt-1.0.json' with { type: 'json' };
import capacitorDictionary from '../../dictionary/capacitor-1.0.json' with { type: 'json' };
import comparatorDictionary from '../../dictionary/comparator-1.0.json' with { type: 'json' };
import crystalDictionary from '../../dictionary/crystal-1.0.json' with { type: 'json' };
import dacDictionary from '../../dictionary/dac-1.0.json' with { type: 'json' };
import dcDcDictionary from '../../dictionary/dc_dc-1.0.json' with { type: 'json' };
import diodeDictionary from '../../dictionary/diode-1.0.json' with { type: 'json' };
import inductorDictionary from '../../dictionary/inductor-1.0.json' with { type: 'json' };
import jfetDictionary from '../../dictionary/jfet-1.0.json' with { type: 'json' };
import laserDiodeDictionary from '../../dictionary/laser_diode-1.0.json' with { type: 'json' };
import ldoDictionary from '../../dictionary/ldo-1.0.json' with { type: 'json' };
import ledDictionary from '../../dictionary/led-1.0.json' with { type: 'json' };
import mosfetDictionary from '../../dictionary/mosfet-1.0.json' with { type: 'json' };
import opAmpDictionary from '../../dictionary/op_amp-1.0.json' with { type: 'json' };
import optocouplerDictionary from '../../dictionary/optocoupler-1.0.json' with { type: 'json' };
import oscillatorDictionary from '../../dictionary/oscillator-1.0.json' with { type: 'json' };
import photodiodeDictionary from '../../dictionary/photodiode-1.0.json' with { type: 'json' };
import resistorDictionary from '../../dictionary/resistor-1.0.json' with { type: 'json' };
import voltageReferenceDictionary from '../../dictionary/voltage_reference-1.0.json' with { type: 'json' };
export { datasheetSchema, adcDictionary, analogSwitchDictionary, bjtDictionary, capacitorDictionary, comparatorDictionary, crystalDictionary, dacDictionary, dcDcDictionary, diodeDictionary, inductorDictionary, jfetDictionary, laserDiodeDictionary, ldoDictionary, ledDictionary, mosfetDictionary, opAmpDictionary, optocouplerDictionary, oscillatorDictionary, photodiodeDictionary, resistorDictionary, voltageReferenceDictionary };
export const dictionaries = { 'adc': adcDictionary, 'analog_switch': analogSwitchDictionary, 'bjt': bjtDictionary, 'capacitor': capacitorDictionary, 'comparator': comparatorDictionary, 'crystal': crystalDictionary, 'dac': dacDictionary, 'dc_dc': dcDcDictionary, 'diode': diodeDictionary, 'inductor': inductorDictionary, 'jfet': jfetDictionary, 'laser_diode': laserDiodeDictionary, 'ldo': ldoDictionary, 'led': ledDictionary, 'mosfet': mosfetDictionary, 'op_amp': opAmpDictionary, 'optocoupler': optocouplerDictionary, 'oscillator': oscillatorDictionary, 'photodiode': photodiodeDictionary, 'resistor': resistorDictionary, 'voltage_reference': voltageReferenceDictionary };
export const SCHEMA_VERSION = '1.0';
